name: Build branch

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: 'Java 17'
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 17

    - name: Build
      run: ./gradlew build --stacktrace
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
